[book]
title = "@connorjs"
authors = ["@connorjs"]
description = "My public website."
src = "docs"
language = "en-US"

[build]
build-dir = "book"  # Update mdbook.yml if you change!

[output.html]
default-theme = "light"
preferred-dark-theme = "dark"
curly-quotes = true
git-repository-url = "https://github.com/connorjs/connorjs.github.io"
edit-url-template = "https://github.com/connorjs/connorjs.github.io/edit/main/{path}"
input-404 = "404.md"

[output.html.fold]
enable = true
level = 1
